deploy:
  provider: s3
  access_key_id: AKIAJOGQRRJ5N54ZLC6A
  secret_access_key:
    secure: NvuSQDjaSxcTb/jtGK7QNTXzueS0WFBLiSsLDOl61R8eyjEJOOkwKZyBpZacZsCdNUQObtB/w3T9bfHL3NsVSJUoDLXXJacmG/HU7qPhgEexa6Gd3EMB+1Lybu9p+S6IlWfOfgdyDmXWjx1kPZGLbhbhZ1p6IMqQQgVhHPbrgLg=
  bucket: www.restdoc.org
  skip_cleanup: true
  endpoint: "www.restdoc.org.s3-website-eu-central-1.amazonaws.com"
  region: "eu-central-1"
  detect_encoding: true